CREATE DATABASE IF NOT EXISTS nest_guard_db;
USE nest_guard_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    address TEXT,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    telephone VARCHAR(15),
    city VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

  

USE nest_guard_db;

ALTER TABLE users
ADD COLUMN type VARCHAR(100),
ADD COLUMN timing VARCHAR(100),
ADD COLUMN experience VARCHAR(100),
ADD COLUMN baby_name VARCHAR(100),
ADD COLUMN baby_age VARCHAR(50),
ADD COLUMN feeding VARCHAR(100),
ADD COLUMN pref1 VARCHAR(100),
ADD COLUMN pref2 VARCHAR(100),
ADD COLUMN pref3 VARCHAR(100),
ADD COLUMN pref4 VARCHAR(100),
ADD COLUMN profile_image LONGTEXT;

SELECT * FROM users;

